spring.application.name=graphql-books

spring.datasource.url=jdbc:postgresql://localhost:5432/gbooks
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG

spring.graphql.graphiql.enabled=true
